name: Your New Jekyll Site
baseurl: /
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  projects:
    output: true
    permalink: /:name