projects: 
- {name: Typo Internation}
- {name: American Apparel}
- {name: Crisp Icons}
- {name: Flat mobile}
- {name: Fresh It Up}
- {name: Timeline page}
- {name: Typo Internation}
- {name: Strips & Co}